// <auto-generated />
using System;
using CostWise.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CostWise.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CostWiseDbContext))]
    [Migration("20261002101038_AddVictorySnapshotProduct")]
    partial class AddVictorySnapshotProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("CostWise.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("CostWise.Core.Entities.CommercialPriceList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CurrencyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("SellUnit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CommercialPriceLists");
                });

            modelBuilder.Entity("CostWise.Core.Entities.CommercialPriceListBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommercialPriceListId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PriceBookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PriceBookId")
                        .IsUnique();

                    b.HasIndex("CommercialPriceListId", "PriceBookId")
                        .IsUnique();

                    b.ToTable("CommercialPriceListBooks");
                });

            modelBuilder.Entity("CostWise.Core.Entities.CostingScenario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AdditiveOptionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExportDocCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExportDocOptionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FormulationId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MarginPercent")
                        .HasPrecision(8, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Market")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PackingCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PackingOptionId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SnapshotConversionCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SnapshotRmCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SnapshotSellingPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SnapshotTotalCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SpecialAdditiveCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TransportationCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AdditiveOptionId");

                    b.HasIndex("ExportDocOptionId");

                    b.HasIndex("FormulationId");

                    b.HasIndex("PackingOptionId");

                    b.ToTable("CostingScenarios");
                });

            modelBuilder.Entity("CostWise.Core.Entities.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBase")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("KesPerUnit")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("CostWise.Core.Entities.FeedType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("FeedTypes");
                });

            modelBuilder.Entity("CostWise.Core.Entities.Formulation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("FeedTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImportBatchId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ImportedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Revision")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("SizeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SystemId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("FeedTypeId");

                    b.HasIndex("SizeId");

                    b.HasIndex("SpeciesId");

                    b.HasIndex("SubCategoryId");

                    b.HasIndex("SystemId")
                        .IsUnique();

                    b.ToTable("Formulations");
                });

            modelBuilder.Entity("CostWise.Core.Entities.FormulationChangeLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FormulationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImportBatchId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAtUtc");

                    b.HasIndex("FormulationId");

                    b.HasIndex("SystemId");

                    b.ToTable("FormulationChangeLogs");
                });

            modelBuilder.Entity("CostWise.Core.Entities.FormulationIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FormulationId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("InclusionPercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("RawIngredientId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RawIngredientId");

                    b.HasIndex("FormulationId", "RawIngredientId")
                        .IsUnique();

                    b.ToTable("FormulationIngredients");
                });

            modelBuilder.Entity("CostWise.Core.Entities.FormulationSpec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FormulationId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("MaxValue")
                        .HasPrecision(12, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MinValue")
                        .HasPrecision(12, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("SpecParameterId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("TargetValue")
                        .HasPrecision(12, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SpecParameterId");

                    b.HasIndex("FormulationId", "SpecParameterId")
                        .IsUnique();

                    b.ToTable("FormulationSpecs");
                });

            modelBuilder.Entity("CostWise.Core.Entities.PriceBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AdditiveOptionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DisplayCurrencyId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ExportDocCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExportDocOptionId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MarginPercent")
                        .HasPrecision(8, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PackingCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PackingOptionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PriceUnit")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("RoundBagTo")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RoundMtTo")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SpecialAdditiveCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TransportationCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AdditiveOptionId");

                    b.HasIndex("DisplayCurrencyId");

                    b.HasIndex("ExportDocOptionId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PackingOptionId");

                    b.ToTable("PriceBooks");
                });

            modelBuilder.Entity("CostWise.Core.Entities.PriceBookFormulation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FormulationId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("OverrideSellPriceBag")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OverrideSellPriceMt")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("PriceBookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FormulationId");

                    b.HasIndex("PriceBookId", "FormulationId")
                        .IsUnique();

                    b.ToTable("PriceBookFormulations");
                });

            modelBuilder.Entity("CostWise.Core.Entities.PricingCostOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Kind", "Name")
                        .IsUnique();

                    b.ToTable("PricingCostOptions");
                });

            modelBuilder.Entity("CostWise.Core.Entities.ProductionGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ProductionGroups");
                });

            modelBuilder.Entity("CostWise.Core.Entities.ProductionGroupFormulation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FormulationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductionGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FormulationId");

                    b.HasIndex("ProductionGroupId", "FormulationId")
                        .IsUnique();

                    b.ToTable("ProductionGroupFormulations");
                });

            modelBuilder.Entity("CostWise.Core.Entities.RawIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePerMt")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("RawIngredients");
                });

            modelBuilder.Entity("CostWise.Core.Entities.RawIngredientPriceHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExchangeRateKesPerUsd")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePerMt")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePerMtUsd")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("RawIngredientId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RawIngredientId", "ChangedAtUtc");

                    b.ToTable("RawIngredientPriceHistories");
                });

            modelBuilder.Entity("CostWise.Core.Entities.Size", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ConversionCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiameterMm")
                        .HasPrecision(8, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("FeedTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FeedTypeId");

                    b.ToTable("Sizes");
                });

            modelBuilder.Entity("CostWise.Core.Entities.SpecParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SpecParameters");
                });

            modelBuilder.Entity("CostWise.Core.Entities.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Species");
                });

            modelBuilder.Entity("CostWise.Core.Entities.SubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SubCategories");
                });

            modelBuilder.Entity("CostWise.Core.Entities.VictoryReportSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookAId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BookAMarginPercent")
                        .HasPrecision(8, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("BookBId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BookBMarginPercent")
                        .HasPrecision(8, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("BriefJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookAId");

                    b.HasIndex("BookBId");

                    b.HasIndex("CreatedAtUtc");

                    b.ToTable("VictoryReportSnapshots");
                });

            modelBuilder.Entity("CostWise.Core.Entities.VictoryReportSnapshotLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BookRole")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("FeedTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FormulationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("FormulationId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PriceBookId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("SellBag")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SellMt")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("SizeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SnapshotId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FormulationId");

                    b.HasIndex("PriceBookId");

                    b.HasIndex("SnapshotId", "PriceBookId", "FormulationId")
                        .IsUnique();

                    b.ToTable("VictoryReportSnapshotLines");
                });

            modelBuilder.Entity("CostWise.Core.Entities.CommercialPriceList", b =>
                {
                    b.HasOne("CostWise.Core.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("CostWise.Core.Entities.CommercialPriceListBook", b =>
                {
                    b.HasOne("CostWise.Core.Entities.CommercialPriceList", "CommercialPriceList")
                        .WithMany("Books")
                        .HasForeignKey("CommercialPriceListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CostWise.Core.Entities.PriceBook", "PriceBook")
                        .WithMany()
                        .HasForeignKey("PriceBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommercialPriceList");

                    b.Navigation("PriceBook");
                });

            modelBuilder.Entity("CostWise.Core.Entities.CostingScenario", b =>
                {
                    b.HasOne("CostWise.Core.Entities.PricingCostOption", "AdditiveOption")
                        .WithMany()
                        .HasForeignKey("AdditiveOptionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CostWise.Core.Entities.PricingCostOption", "ExportDocOption")
                        .WithMany()
                        .HasForeignKey("ExportDocOptionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CostWise.Core.Entities.Formulation", "Formulation")
                        .WithMany("CostingScenarios")
                        .HasForeignKey("FormulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CostWise.Core.Entities.PricingCostOption", "PackingOption")
                        .WithMany()
                        .HasForeignKey("PackingOptionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AdditiveOption");

                    b.Navigation("ExportDocOption");

                    b.Navigation("Formulation");

                    b.Navigation("PackingOption");
                });

            modelBuilder.Entity("CostWise.Core.Entities.Formulation", b =>
                {
                    b.HasOne("CostWise.Core.Entities.Category", "Category")
                        .WithMany("Formulations")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CostWise.Core.Entities.FeedType", "FeedType")
                        .WithMany("Formulations")
                        .HasForeignKey("FeedTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CostWise.Core.Entities.Size", "Size")
                        .WithMany("Formulations")
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CostWise.Core.Entities.Species", "Species")
                        .WithMany("Formulations")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CostWise.Core.Entities.SubCategory", "SubCategory")
                        .WithMany("Formulations")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("FeedType");

                    b.Navigation("Size");

                    b.Navigation("Species");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("CostWise.Core.Entities.FormulationChangeLog", b =>
                {
                    b.HasOne("CostWise.Core.Entities.Formulation", "Formulation")
                        .WithMany("ChangeLogs")
                        .HasForeignKey("FormulationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Formulation");
                });

            modelBuilder.Entity("CostWise.Core.Entities.FormulationIngredient", b =>
                {
                    b.HasOne("CostWise.Core.Entities.Formulation", "Formulation")
                        .WithMany("Ingredients")
                        .HasForeignKey("FormulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CostWise.Core.Entities.RawIngredient", "RawIngredient")
                        .WithMany("FormulationIngredients")
                        .HasForeignKey("RawIngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Formulation");

                    b.Navigation("RawIngredient");
                });

            modelBuilder.Entity("CostWise.Core.Entities.FormulationSpec", b =>
                {
                    b.HasOne("CostWise.Core.Entities.Formulation", "Formulation")
                        .WithMany("Specs")
                        .HasForeignKey("FormulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CostWise.Core.Entities.SpecParameter", "SpecParameter")
                        .WithMany("FormulationSpecs")
                        .HasForeignKey("SpecParameterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Formulation");

                    b.Navigation("SpecParameter");
                });

            modelBuilder.Entity("CostWise.Core.Entities.PriceBook", b =>
                {
                    b.HasOne("CostWise.Core.Entities.PricingCostOption", "AdditiveOption")
                        .WithMany()
                        .HasForeignKey("AdditiveOptionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CostWise.Core.Entities.Currency", "DisplayCurrency")
                        .WithMany()
                        .HasForeignKey("DisplayCurrencyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CostWise.Core.Entities.PricingCostOption", "ExportDocOption")
                        .WithMany()
                        .HasForeignKey("ExportDocOptionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CostWise.Core.Entities.PricingCostOption", "PackingOption")
                        .WithMany()
                        .HasForeignKey("PackingOptionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AdditiveOption");

                    b.Navigation("DisplayCurrency");

                    b.Navigation("ExportDocOption");

                    b.Navigation("PackingOption");
                });

            modelBuilder.Entity("CostWise.Core.Entities.PriceBookFormulation", b =>
                {
                    b.HasOne("CostWise.Core.Entities.Formulation", "Formulation")
                        .WithMany()
                        .HasForeignKey("FormulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CostWise.Core.Entities.PriceBook", "PriceBook")
                        .WithMany("Formulations")
                        .HasForeignKey("PriceBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Formulation");

                    b.Navigation("PriceBook");
                });

            modelBuilder.Entity("CostWise.Core.Entities.ProductionGroupFormulation", b =>
                {
                    b.HasOne("CostWise.Core.Entities.Formulation", "Formulation")
                        .WithMany()
                        .HasForeignKey("FormulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CostWise.Core.Entities.ProductionGroup", "ProductionGroup")
                        .WithMany("Formulations")
                        .HasForeignKey("ProductionGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Formulation");

                    b.Navigation("ProductionGroup");
                });

            modelBuilder.Entity("CostWise.Core.Entities.RawIngredientPriceHistory", b =>
                {
                    b.HasOne("CostWise.Core.Entities.RawIngredient", "RawIngredient")
                        .WithMany("PriceHistory")
                        .HasForeignKey("RawIngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RawIngredient");
                });

            modelBuilder.Entity("CostWise.Core.Entities.Size", b =>
                {
                    b.HasOne("CostWise.Core.Entities.FeedType", "FeedType")
                        .WithMany("Sizes")
                        .HasForeignKey("FeedTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FeedType");
                });

            modelBuilder.Entity("CostWise.Core.Entities.VictoryReportSnapshot", b =>
                {
                    b.HasOne("CostWise.Core.Entities.PriceBook", "BookA")
                        .WithMany()
                        .HasForeignKey("BookAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CostWise.Core.Entities.PriceBook", "BookB")
                        .WithMany()
                        .HasForeignKey("BookBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BookA");

                    b.Navigation("BookB");
                });

            modelBuilder.Entity("CostWise.Core.Entities.VictoryReportSnapshotLine", b =>
                {
                    b.HasOne("CostWise.Core.Entities.Formulation", "Formulation")
                        .WithMany()
                        .HasForeignKey("FormulationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CostWise.Core.Entities.PriceBook", "PriceBook")
                        .WithMany()
                        .HasForeignKey("PriceBookId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CostWise.Core.Entities.VictoryReportSnapshot", "Snapshot")
                        .WithMany("Lines")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Formulation");

                    b.Navigation("PriceBook");

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("CostWise.Core.Entities.Category", b =>
                {
                    b.Navigation("Formulations");
                });

            modelBuilder.Entity("CostWise.Core.Entities.CommercialPriceList", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("CostWise.Core.Entities.FeedType", b =>
                {
                    b.Navigation("Formulations");

                    b.Navigation("Sizes");
                });

            modelBuilder.Entity("CostWise.Core.Entities.Formulation", b =>
                {
                    b.Navigation("ChangeLogs");

                    b.Navigation("CostingScenarios");

                    b.Navigation("Ingredients");

                    b.Navigation("Specs");
                });

            modelBuilder.Entity("CostWise.Core.Entities.PriceBook", b =>
                {
                    b.Navigation("Formulations");
                });

            modelBuilder.Entity("CostWise.Core.Entities.ProductionGroup", b =>
                {
                    b.Navigation("Formulations");
                });

            modelBuilder.Entity("CostWise.Core.Entities.RawIngredient", b =>
                {
                    b.Navigation("FormulationIngredients");

                    b.Navigation("PriceHistory");
                });

            modelBuilder.Entity("CostWise.Core.Entities.Size", b =>
                {
                    b.Navigation("Formulations");
                });

            modelBuilder.Entity("CostWise.Core.Entities.SpecParameter", b =>
                {
                    b.Navigation("FormulationSpecs");
                });

            modelBuilder.Entity("CostWise.Core.Entities.Species", b =>
                {
                    b.Navigation("Formulations");
                });

            modelBuilder.Entity("CostWise.Core.Entities.SubCategory", b =>
                {
                    b.Navigation("Formulations");
                });

            modelBuilder.Entity("CostWise.Core.Entities.VictoryReportSnapshot", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
