<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CostWise.Core\CostWise.Core.csproj" />
    <ProjectReference Include="..\CostWise.Infrastructure\CostWise.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.104.2" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
      <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="QuestPDF" Version="2024.10.3" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationTitle>OBAID Pricing</ApplicationTitle>
    <Product>OBAID Pricing</Product>
    <AssemblyTitle>OBAID Pricing</AssemblyTitle>
    <ApplicationIcon>Assets\obaid-pricing-logo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\obaid-pricing-logo.png" />
    <Resource Include="Assets\obaid-pricing-logo-dark.png" />
    <None Include="Assets\obaid-pricing-logo.ico" />
  </ItemGroup>

</Project>
